name = "kolmogorov_extension4"
defaultTargets = ["KolmogorovExtension4"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0"

[[lean_lib]]
name = "KolmogorovExtension4"
